VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "InitialValuesPOheader"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit



Public InitDocType As String
Public InitPO As String
Public InitShipperName As String
Public InitShipperCode As String
Public InitChargeTo As String
Public InitPriority As String
Public InitBuyer As String
Public InitOriginator As String
Public InitCategoryCode As String
Public InitToBeUsedFor As String
Public InitSupplier As String
Public InitCurrency As String
Public InitCompanyName As String
Public InitCompanyCode As String
Public InitInvLocation As String
Public InitConfirmingOrder As Boolean
Public InitCondition As String
Public InitDelivery As String
Public InitFrmStkMst As Boolean
Public InitSite As String
Public InitShipTo As String
Public InitRequestedDate As Date
'LblDateSent
Public InitpoDate As Date
Public initServiceCode As String
Public initServicedesc As String
